
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is Clang, found in:
        C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/3.27.8/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is Clang, found in:
        C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/3.27.8/CompilerIdCXX/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-5f4yzw"
      binary: "C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-5f4yzw"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-5f4yzw'
        
        Run Build Command(s): D:/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_21fac\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_21fac.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_21fac.dir\\build
        Building C object CMakeFiles/cmTC_21fac.dir/CMakeCCompilerABI.c.obj
        	C:\\PROGRA~1\\LLVM\\bin\\clang.exe   -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -MD -MT CMakeFiles\\cmTC_21fac.dir\\CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_21fac.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles\\cmTC_21fac.dir\\CMakeCCompilerABI.c.obj -c D:\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c
        Linking C executable cmTC_21fac.exe
        	C:\\PROGRA~1\\LLVM\\bin\\clang.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console @CMakeFiles\\cmTC_21fac.dir\\objects1.rsp -o cmTC_21fac.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_21fac.lib -Xlinker /pdb:C:\\Users\\23766\\Desktop\\cppMonkey\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-5f4yzw\\cmTC_21fac.pdb -Xlinker /version:0.0
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-vvtquo"
      binary: "C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-vvtquo"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-vvtquo'
        
        Run Build Command(s): D:/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_04d49\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_04d49.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_04d49.dir\\build
        Building CXX object CMakeFiles/cmTC_04d49.dir/CMakeCXXCompilerABI.cpp.obj
        	C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE   -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -MD -MT CMakeFiles\\cmTC_04d49.dir\\CMakeCXXCompilerABI.cpp.obj -MF CMakeFiles\\cmTC_04d49.dir\\CMakeCXXCompilerABI.cpp.obj.d -o CMakeFiles\\cmTC_04d49.dir\\CMakeCXXCompilerABI.cpp.obj -c D:\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_04d49.exe
        	C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console @CMakeFiles\\cmTC_04d49.dir\\objects1.rsp -o cmTC_04d49.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_04d49.lib -Xlinker /pdb:C:\\Users\\23766\\Desktop\\cppMonkey\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-vvtquo\\cmTC_04d49.pdb -Xlinker /version:0.0
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/Internal/FeatureTesting.cmake:34 (try_compile)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/Internal/FeatureTesting.cmake:83 (_record_compiler_features)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/Compiler/CMakeCommonCompilerMacros.cmake:121 (_record_compiler_features_cxx)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompileFeatures.cmake:70 (cmake_record_cxx_compile_features)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:70 (CMAKE_DETERMINE_COMPILE_FEATURES)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compile features"
    directories:
      source: "C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-tg80iw"
      binary: "C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-tg80iw"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_FEATURE_TEST"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-tg80iw'
        
        Run Build Command(s): D:/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_030a8\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_030a8.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_030a8.dir\\build
        Building CXX object CMakeFiles/cmTC_030a8.dir/feature_tests.cxx.obj
        	C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE   -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview   -std=c++14 -MD -MT CMakeFiles\\cmTC_030a8.dir\\feature_tests.cxx.obj -MF CMakeFiles\\cmTC_030a8.dir\\feature_tests.cxx.obj.d -o CMakeFiles\\cmTC_030a8.dir\\feature_tests.cxx.obj -c C:\\Users\\23766\\Desktop\\cppMonkey\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-tg80iw\\feature_tests.cxx
        Linking CXX executable cmTC_030a8.exe
        	C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console @CMakeFiles\\cmTC_030a8.dir\\objects1.rsp -o cmTC_030a8.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_030a8.lib -Xlinker /pdb:C:\\Users\\23766\\Desktop\\cppMonkey\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-tg80iw\\cmTC_030a8.pdb -Xlinker /version:0.0  @CMakeFiles\\cmTC_030a8.dir\\linkLibs.rsp
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/Internal/FeatureTesting.cmake:34 (try_compile)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/Internal/FeatureTesting.cmake:83 (_record_compiler_features)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/Compiler/CMakeCommonCompilerMacros.cmake:129 (_record_compiler_features_cxx)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompileFeatures.cmake:70 (cmake_record_cxx_compile_features)"
      - "D:/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:70 (CMAKE_DETERMINE_COMPILE_FEATURES)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compile features"
    directories:
      source: "C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-baz5ax"
      binary: "C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-baz5ax"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_FEATURE_TEST"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/23766/Desktop/cppMonkey/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-baz5ax'
        
        Run Build Command(s): D:/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_b4e7a\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_b4e7a.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_b4e7a.dir\\build
        Building CXX object CMakeFiles/cmTC_b4e7a.dir/feature_tests.cxx.obj
        	C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE   -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview   -std=c++14 -MD -MT CMakeFiles\\cmTC_b4e7a.dir\\feature_tests.cxx.obj -MF CMakeFiles\\cmTC_b4e7a.dir\\feature_tests.cxx.obj.d -o CMakeFiles\\cmTC_b4e7a.dir\\feature_tests.cxx.obj -c C:\\Users\\23766\\Desktop\\cppMonkey\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-baz5ax\\feature_tests.cxx
        Linking CXX executable cmTC_b4e7a.exe
        	C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console @CMakeFiles\\cmTC_b4e7a.dir\\objects1.rsp -o cmTC_b4e7a.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_b4e7a.lib -Xlinker /pdb:C:\\Users\\23766\\Desktop\\cppMonkey\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-baz5ax\\cmTC_b4e7a.pdb -Xlinker /version:0.0  @CMakeFiles\\cmTC_b4e7a.dir\\linkLibs.rsp
        
      exitCode: 0
...
